feat: implement sigil
Netnod/robust-tjanst pull request #43
Opened 2022-01-12 10:18 UTC by izabellalarsson

General work is done. 

TODO: 
- [ ] Get new design from Johan and update
- [ ] Connect to db and check if all tests passed or not.

2022-01-13 13:16 UTC, irony commented
Great! 

Since I started thinking about this feature in december I thought it could be good to just leave my thoughts here. You might have already found other better ways to do it, if so just ignore this. 

The idea was that every time a sigill is called - we check the cache and see if it's still valid- otherwise we schedule a new test (add a job to bullMQ) and serve a success badge (or previous result) while the test is running. That way we can rely on the badge as the initiator of a recurrent test without having to first implement the whole registration process.

2022-01-21 15:33 UTC, izabellalarsson commented
<img width="983" alt="Screenshot 2022-01-21 at 16 33 06" src="https://user-images.githubusercontent.com/36758509/150554574-df3e9434-2342-4f58-b9b0-3f6b883a0b82.png">

2022-01-26 09:39 UTC, izabellalarsson commented
<img width="600" alt="Screenshot 2022-01-26 at 10 38 41" src="https://user-images.githubusercontent.com/36758509/151139231-03107c99-a5f4-4c10-8b66-359eeac33216.png">
<img width="600" alt="Screenshot 2022-01-26 at 10 39 09" src="https://user-images.githubusercontent.com/36758509/151139298-4b381c98-0708-4364-aaaf-e9ef97d8b622.png">

2022-01-27 08:01 UTC, mull approved these changes

2022-01-27 08:08 UTC, irony requested changes
En liten copyändring i övrigt toppen!

2022-01-27 08:08 UTC, irony commented on packages/web/src/views/tests/show.pug
> +      p <i>Obs. Detta är en beta version, en ny embedkod kommer att komma senare.</i>
Obs! Detta är en betaversion, eventuellt kan du behöva byta ut till ny embedkod senare.

2022-01-27 08:10 UTC, irony commented on packages/web/src/views/tests/show.pug
> +      p <i>Obs. Detta är en beta version, en ny embedkod kommer att komma senare.</i>
Vi kommer antagligen inte behöva en ny embedkod framöver så jag skrev ett förslag ovan om att den KAN ändras.

2022-01-27 09:33 UTC, merged